CMake support
- Implemented support for Linux, Windows, MacOS, FreeBSD
  * CMakeLists includes build pcm* executables and install them
  *  with dependencies
- 'Doc', 'scripts', 'examples' and 'tests' reorganization
  * 'Doc': updated README, *HOW_TO.txt and related files with CMake
  *  approach steps;
  *  replaced absolute pathes with relative to current branch
  * 'scripts' contians existed bash and python scripts
  * 'examples' contains c_example (static and shared)
  * 'tests' contains 'daemon alignment test', test.sh, urltest
    ** CMake support for urltest on MacOs is not added due to fail on
    **  Darwin 21.1.0 with "error: use of undeclared identifier
    ** 'sched_setscheduler'"
- Added CI adaptation (gcc-*, windows, cppcheck, scan-build, kw)
- Added CMake steps to external build files like:
  * Dockerfile, *.spec, cirrus.yml, ..
- Removed unnecessary folders and files