Fix msrmain.c Complie error
When I using mymake.bat and WDK 7600.16385.1 x64 Free Build Environment
I got error C2275 in line 160.

Because can't have a variable declared in the middle of the scope.
So i modify the code.