Introduce Raptor Lake IDs
This commit introduces device IDs 0xB7, 0xBA, and 0xBF. See kernel
family mappings at [1]. From a performance event perspective, ADL and
RPL share event files [2].

Before:
  ~/pcm/build/bin$ ./pcm-core
  <snip>
  CPU model number         : 183
  Error: unsupported processor.

This change:
  ~/pcm/build/bin$ sudo ./pcm-core
  <snip>
  Time elapsed: 1009 ms
  txn_rate: 1

  Core | IPC | Instructions  |  Cycles  | RefCycles | Event0  | Event1  | Event2  | Event3  | Event4  | Event5
     0   0.48         738 K     1543 K      4678 K       0         0         0         0         0         0
     1   0.38         115 K      306 K       930 K       0         0         0         0         0         0
     2   1.19        1082 K      908 K      2752 K       0         0         0         0         0         0
  <snip>

[1] https://github.com/torvalds/linux/blob/bb1a1146/arch/x86/include/asm/intel-family.h#L114
[2] https://github.com/intel/perfmon/blob/0eefc09e/mapfile.csv#L138