Revert "use c++ threads to simplify code"
This reverts commit 2cb4842dee861cdc13435d46565feb3c9a81e47c.

due to the error in PCM-service
error C1189: #error :  <thread> is not supported when compiling with /clr
or /clr:pure.